import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import { bibliography } from '../bibliography';
import type { SettlementMapLocaleContent, SettlementMapUI } from '../entry';

const ui: SettlementMapUI = {
  intro: 'Lay out a place worth exploring. Pick the landscape, settlement type, and building character, then correct the generated map with a right click or long press.', seedLabel: 'Village name seed', seedHint: 'The seed chooses a different deterministic layout pattern within the selected settlement type.', randomSeed: 'Create a new village name', environmentLabel: 'Landscape', forest: 'Forest', plains: 'Plains', coast: 'Coast', river: 'River', mountain: 'Mountain', styleLabel: 'Village character', styleHint: 'Choose an architectural identity: era, geography, roofs, materials, and details all change.', styleTimber: 'Timber', styleStone: 'Stone', styleCoastal: 'Coastal', styleHighland: 'Highland', styleMedieval: 'Medieval', styleEdo: 'Edo', styleSahelian: 'Sahelian', sizeLabel: 'Settlement footprint', hamlet: 'Hamlet', hamletHint: 'Small stop', village: 'Village', villageHint: 'Local base', town: 'Town', townHint: 'Busy hub', homesLabel: 'Homes', homesHint: 'Each footprint has its own starting size and core services. Fine tune the homes after choosing one.', servicesLabel: 'Services to place', serviceListHint: 'Choose presets or add a named landmark for this settlement. Custom services stay in this browser.', newServicePlaceholder: 'Add a service or landmark', addService: 'Add', removeService: 'Remove', serviceTavern: 'Tavern', serviceSmithy: 'Smithy', serviceTemple: 'Temple', serviceMarket: 'Market', serviceStable: 'Stable', serviceHall: 'Hall', generate: 'Regenerate map', mapRegionLabel: 'Editable RPG settlement map', mapSummary: 'Village plan', buildings: 'Buildings', paths: 'Paths', services: 'Services', terrain: 'Water cells', legendLabel: 'Map legend', legendHome: 'Home', legendService: 'Service mark', legendPath: 'Road', legendWater: 'Water', legendWild: 'Trees', editLabel: 'Edit the map directly', toolSelect: 'Inspect', toolBuilding: 'Building', toolPath: 'Road', toolWater: 'Water', toolTree: 'Tree', toolErase: 'Erase', serviceSelectLabel: 'New building mark', clickHint: 'Right click or long press the plan to edit a cell.', selectedHint: 'Cell selected at', shareLink: 'Copy share link', linkCopied: 'Share link copied', exportPng: 'PNG', exportSvg: 'SVG', exportJson: 'Save JSON', importJson: 'Open JSON', importError: 'That file is not a valid settlement map.', mapData: 'Map data', readyBadge: 'Ready to explore', serviceNone: 'No mark', contextMenuLabel: 'Map cell actions', contextInspect: 'Inspect cell', contextBuilding: 'Add building', contextPath: 'Add road', contextWater: 'Add water', contextTree: 'Add tree', contextErase: 'Erase cell',
};

const faq = [
  { question: 'What does this RPG settlement map generator create?', answer: 'It creates a reproducible overhead exploration map for a hamlet, village, or town. The map combines a settlement footprint with homes, roads, services, plazas, water, trees, and the surrounding landscape, so the place feels like part of a wider region instead of a disconnected pile of buildings. It is designed for RPG worldbuilding, campaign preparation, travel scenes, clues, factions, and points of interest rather than tactical combat grids.' },
  { question: 'Does the seed really change the settlement layout?', answer: 'Yes. The seed is not only a name. It drives a deterministic layout variant inside the selected settlement type, so two seeds can produce different road patterns, house positions, spacing, service assignments, and wild growth while still respecting the urban grammar of a hamlet, village, or town. Reusing the same seed and settings rebuilds the same starting map.' },
  { question: 'Which settlement sizes are available?', answer: 'Hamlet, village, and town each have a different footprint and starting logic. Hamlets support small communities, villages create a more developed local base, and towns make room for denser routes, more services, and broader exploration. The home count reacts to the selected footprint, while still allowing a smaller or larger result within that type range.' },
  { question: 'Can I choose the architectural style of the settlement?', answer: 'Yes. Choose Timber, Stone, Coastal, Highland, Medieval, Edo, or Sahelian. The style changes the visual language of houses, including roof shape, wall treatment, doors, windows, texture, colour accents, and the way nearby trees are drawn. It gives the same settlement generator a different regional or historical identity.' },
  { question: 'Can I choose the landscape around the settlement?', answer: 'Yes. Choose forest, plains, coast, river, or mountain. The landscape remains the visual context around the settlement and influences water, vegetation, and terrain details, so the village does not always become the only thing on the map. Forest and wild growth can occupy the surrounding space while the settlement stays readable at the centre.' },
  { question: 'How are services placed?', answer: 'Built-in services include Tavern, Smithy, Temple, Market, Stable, and Hall, and you can add named custom services or landmarks. The generator assigns them with deterministic weights instead of always attaching them to the first few houses: Hall and similar civic services tend toward the centre, while Stable and Smithy tend toward the edge and outer roads, with controlled variation so every settlement does not follow the exact same pattern. Service labels use the full name and appear on readable signs above the building.' },
  { question: 'Can I add my own services and keep them in a shared map?', answer: 'Yes. Add a custom service or landmark to the dynamic list and it is saved in local storage for later maps. Custom entries can be removed whenever you want, while the built-in service presets remain available. When you copy a share link or save JSON, the custom service catalog and the marks already placed on the map travel with the settlement.' },
  { question: 'Can I edit the generated RPG map directly?', answer: 'Yes. Right-click a map cell on desktop or long-press it on touch devices to open the contextual editor. From there you can inspect the cell, add a building, draw a road, paint water, add a tree, or erase it. The contextual menu repositions itself when it would otherwise be clipped by the map or viewport.' },
  { question: 'How do roads and water behave when I edit them?', answer: 'Roads are built as a connected graph with clean junctions, including places where three or four paths meet. Painting water affects the exact selected cell. Adjacent water cells join visually into a river, a small pond, or a broader lake shape as the component grows, so manual edits respond to their neighbours instead of leaving isolated marks.' },
  { question: 'How can I share or reproduce a settlement for another session?', answer: 'Copy the share link to send a complete editable settlement to another person. It preserves the seed, landscape, footprint, home count, architectural style, selected services, custom service list, generated buildings, roads, water, trees, and manual edits. The same state can also be saved as JSON and reopened later.' },
  { question: 'Which export should I use for a campaign handout?', answer: 'PNG is convenient for notes, virtual tabletops, and quick sharing. SVG stays sharp for printing and further vector editing. JSON is the full editable map state, so it is the best option when you want to preserve every generated and manually painted detail rather than only export a picture.' },
];
const howTo = [
  { name: 'Start with a memorable seed', text: 'Use the generated compound settlement name or type your own seed. The seed controls a repeatable layout variation, so it changes the arrangement without abandoning the selected settlement type.' },
  { name: 'Choose the landscape and character', text: 'Select forest, plains, coast, river, or mountain, then choose an architectural identity such as Medieval, Edo, Sahelian, Timber, Stone, Coastal, or Highland. The surrounding wild growth and the houses use the selected visual language.' },
  { name: 'Set the settlement footprint and homes', text: 'Choose hamlet, village, or town. Each footprint reacts with its own map scale, home range, layout grammar, and core services, then you can fine tune the number of homes to match the location in your campaign.' },
  { name: 'Add meaningful services', text: 'Select built-in services such as Tavern, Smithy, Temple, Market, Stable, and Hall, or add your own landmarks. Placement uses weighted centre and edge preferences with seeded variation, while custom services persist in the browser and in shared map data.' },
  { name: 'Correct the map in context', text: 'Right-click or long-press any cell. Add buildings, roads, water, or trees, inspect what is already there, or erase a cell. Roads repair their junctions and adjacent water cells recompute their river, pond, or lake shape as you paint.' },
  { name: 'Share and export the finished place', text: 'Copy a link for a complete editable version, save JSON as a source file, or export PNG for a handout and SVG for crisp printing. The map stays useful as both a worldbuilding draft and a practical exploration reference.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'RPG Settlement and Exploration Map Generator', operatingSystem: 'All', applicationCategory: 'GameApplication', description: 'A browser based RPG settlement map generator with deterministic layouts, five landscapes, seven architectural styles, weighted services, connected roads, reactive water, contextual editing, share links, local storage, and PNG, SVG, and JSON exports.' };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'How to make an RPG settlement exploration map', step: howTo.map((item) => ({ '@type': 'HowToStep', name: item.name, text: item.text })) };

export const content: SettlementMapLocaleContent = {
  slug: 'rpg-settlement-exploration-map-generator', title: 'RPG Settlement and Exploration Map Generator', description: 'Generate a deterministic RPG settlement map with landscapes, architectural styles, smart services, connected roads, reactive water, contextual editing, share links, and PNG, SVG, and JSON export.', ui,
  seo: [
    { type: 'title', text: 'Generate a Living RPG Settlement Map', level: 2 },
    { type: 'paragraph', html: 'Build a settlement that gives players somewhere to go, not just a picture of houses. This browser based RPG map generator creates an overhead exploration map where homes, roads, services, plazas, water, trees, and open terrain work together as a place with shape and purpose. Use it for a quick village stop, a faction filled town, a remote hamlet, or the first draft of a location you will keep developing during a campaign.' },
    { type: 'title', text: 'A Seed That Changes the Town Without Losing Its Character', level: 2 },
    { type: 'paragraph', html: 'Every generated settlement starts from a memorable compound name seed. The seed does more than rename the map: it selects a deterministic variation of the layout, including road rhythm, house spacing, service assignment, and surrounding wild growth. Change the seed to explore a new arrangement, then reuse the same seed and settings whenever you need to rebuild the same starting map for your notes, players, or future sessions.' },
    { type: 'list', items: ['Different seeds create different patterns inside the chosen settlement type.', 'The result stays reproducible instead of becoming an untraceable random roll.', 'The settlement remains readable as a hamlet, village, or town while its internal arrangement changes.', 'The same seed can be shared as a stable starting point for collaborative campaign preparation.'] },
    { type: 'title', text: 'Hamlet Village and Town Use Different Urban Grammars', level: 2 },
    { type: 'paragraph', html: 'The footprint selector is not a cosmetic size switch. Hamlets, villages, and towns use different construction patterns, spacing, home ranges, and service expectations. A hamlet can stay under ten houses without looking like a shrunken town, while a town has room for longer routes, more destinations, and a stronger central structure. The home count reacts to the selected footprint so the generated place keeps the right scale.' },
    { type: 'table', headers: ['Footprint', 'Home range', 'Character', 'Best campaign use'], rows: [['Hamlet', '3 to 18', 'Small, sparse, and easy to read at a glance', 'A roadside stop, isolated community, or village edge'], ['Village', '4 to 28', 'A local centre with several routes and landmarks', 'A recurring base, mystery location, or faction hub'], ['Town', '6 to 42', 'A broader network with more services and detours', 'A regional hub, investigation space, or starting settlement']] },
    { type: 'title', text: 'Choose an Architectural Identity', level: 2 },
    { type: 'paragraph', html: 'Give the settlement a visual identity before you start placing details. Timber, Stone, Coastal, Highland, Medieval, Edo, and Sahelian styles alter the houses with different roof profiles, wall colours, doors, windows, textures, and decorative details. The tree language changes with the setting too, from coastal palms and highland conifers to rounded Edo silhouettes, broad medieval canopies, and Sahelian acacia forms. The style makes the map feel like a region, era, or culture rather than a recoloured template.' },
    { type: 'list', items: ['Medieval and Timber support storybook villages, frontier settlements, and woodland communities.', 'Stone and Highland suit rugged, elevated, defensive, or weather exposed places.', 'Coastal introduces a brighter maritime identity with vegetation that belongs near the shore.', 'Edo provides a distinct historical and regional silhouette for streets, houses, and trees.', 'Sahelian gives dryland communities their own architecture, palette, and tree shapes.'] },
    { type: 'title', text: 'Place Services Where They Make Sense', level: 2 },
    { type: 'paragraph', html: 'Services are story anchors with spatial logic. Tavern, Smithy, Temple, Market, Stable, and Hall are not blindly assigned to the first five buildings. Seeded weights choose among suitable candidates, with civic buildings tending toward the centre, stables and smithies favouring outer roads, and other services receiving a useful middle ground with enough variation to avoid a repeated pattern. Add custom services such as a watch post, apothecary, shrine, guildhall, ferry office, or whatever your adventure needs. Full service names appear on large signs above the houses so they stay legible in a town and remain visually attached to the correct building.' },
    { type: 'title', text: 'Let the Landscape Be Part of the Story', level: 2 },
    { type: 'paragraph', html: 'Choose Forest, Plains, Coast, River, or Mountain and let the settlement sit inside that context. The map gives the surrounding landscape room to breathe, with wild growth and terrain framing the populated area instead of turning the village into the only protagonist. A river can define an approach, a forest can hide a path or landmark, and the open ground around a hamlet can communicate isolation before a single encounter is written.' },
    { type: 'title', text: 'Edit the Map Cell by Cell', level: 2 },
    { type: 'paragraph', html: 'The generated plan is a strong starting point, but the contextual editor is where it becomes your location. Right-click on desktop or long-press on a touch screen to open the cell actions exactly where you are working. Inspect a cell, add a building, draw a road, paint water, add a tree, or erase an unwanted mark. The menu repositions itself when the edge of the map would clip it, keeping the editing action available without covering the workspace.' },
    { type: 'list', items: ['Add a missing house, bridge approach, shrine, watch post, field, or other point of interest.', 'Move from generated structure to campaign-specific detail without opening a separate drawing toolbar.', 'Keep manual edits in the same map state as the generated content.', 'Use the same interaction on desktop and touch devices with right click or long press.'] },
    { type: 'title', text: 'Roads and Water Respond to Their Neighbours', level: 2 },
    { type: 'paragraph', html: 'Roads are generated as connected routes rather than decorative disconnected lines. Intersections are drawn cleanly when three or four paths meet, giving the settlement a usable circulation pattern. Water painting is equally reactive: a painted cell remains an exact edit, adjacent cells join into a river or pond, and larger connected groups resolve into a broader lake shape. This makes it practical to sketch a stream bend, extend a shoreline, add a crossing, or reshape a water feature directly on the map.' },
    { type: 'title', text: 'Keep Your Services and Share the Complete Place', level: 2 },
    { type: 'paragraph', html: 'Custom services are saved in local storage so a useful landmark list can grow across maps. Remove custom entries when they no longer belong; built-in presets remain available. When you copy a share link, the recipient gets the complete editable state: seed, footprint, home count, landscape, architectural style, service catalog, service marks, buildings, roads, water, trees, and manual edits. Nothing important is reduced to a screenshot.' },
    { type: 'title', text: 'Export for Notes, Printing, or Continued Editing', level: 2 },
    { type: 'table', headers: ['Format', 'Useful for', 'What it preserves'], rows: [['PNG', 'Virtual tabletops, notes, and quick handouts', 'A ready to view image of the current map'], ['SVG', 'Printing and vector workflows', 'A sharp scalable drawing for larger layouts'], ['JSON', 'Campaign archives and future edits', 'The complete editable settlement state']] },
    { type: 'tip', title: 'A Practical Workflow for Game Night', html: 'Start with a seed, footprint, landscape, and architectural style. Add only the services that can create scenes or clues, then use the contextual editor to place the one bridge, road, tree line, water cell, or outlying house that makes the adventure yours. Copy the share link for the editable master and export a PNG or SVG when you need a clean reference at the table.' },
  ], faq, bibliography, howTo, schemas: [faqSchema, appSchema, howToSchema] as unknown as Record<string, unknown>[],
};
